module.exports = [
  {
    logo: "amazonaws",
    badgeContent: "Amazon AWS",
    color: "232F3E",
    logoColor: "white",
  },
  {
    logo: "ansible",
    badgeContent: "Ansible",
    color: "EE0000",
    logoColor: "white",
  },
  {
    logo: "gnubash",
    badgeContent: "BASH",
    color: "121011",
    logoColor: "white",
  },
  {
    logo: "debian",
    badgeContent: "Debian",
    color: "A81D33",
    logoColor: "white",
  },
  {
    logo: "docker",
    badgeContent: "Docker",
    color: "46a2f1",
    logoColor: "white",
  },
  {
    logo: "express",
    badgeContent: "Express.js",
    color: "404D59",
    logoColor: "white",
  },
  {
    logo: "git",
    badgeContent: "Git",
    color: "F05032",
    logoColor: "white",
  },
  {
    logo: "github",
    badgeContent: "GitHub",
    color: "181717",
    logoColor: "white",
  },
  {
    logo: "githubactions",
    badgeContent: "Github Actions",
    color: "2088FF",
    logoColor: "white",
  },
  {
    logo: "gitlab",
    badgeContent: "Gitlab",
    color: "FC6D26",
    logoColor: "white",
  },
  {
    logo: "go",
    badgeContent: "GO",
    color: "00ADD8",
    logoColor: "white",
  },
  {
    logo: "googlecloud",
    badgeContent: "Google Cloud",
    color: "4285F4",
    logoColor: "white",
  },
  {
    logo: "grafana",
    badgeContent: "Grafana",
    color: "F46800",
    logoColor: "white",
  },
  {
    logo: "helm",
    badgeContent: "Helm",
    color: "091C84",
    logoColor: "white",
  },
  {
    logo: "heroku",
    badgeContent: "Heroku",
    color: "430098",
    logoColor: "white",
  },
  {
    logo: "javascript",
    badgeContent: "Javascript",
    color: "F7DF1E",
    logoColor: "black",
  },
  {
    logo: "kubernetes",
    badgeContent: "Kubernetes",
    color: "316CE6",
    logoColor: "white",
  },
  {
    logo: "linux",
    badgeContent: "Linux",
    color: "FCC624",
    logoColor: "black",
  },
  {
    logo: "manjaro",
    badgeContent: "Manjaro",
    color: "35BF5C",
    logoColor: "white",
  },
  {
    logo: "mongodb",
    badgeContent: "MongoDB",
    color: "47A248",
    logoColor: "white",
  },
  {
    logo: "nginx",
    badgeContent: "Nginx",
    color: "009639",
    logoColor: "white",
  },
  {
    logo: "nginx",
    badgeContent: "Nginx",
    color: "009639",
    logoColor: "white",
  },
  {
    logo: "node.js",
    badgeContent: "Node.js",
    color: "43853D",
    logoColor: "white",
  },
  {
    logo: "postgresql",
    badgeContent: "PostgreSQL",
    color: "4169E1",
    logoColor: "white",
  },
  {
    logo: "prometheus",
    badgeContent: "Prometheus",
    color: "E6522C",
    logoColor: "white",
  },
  {
    logo: "python",
    badgeContent: "Python",
    color: "3776AB",
    logoColor: "white",
  },
  {
    logo: "raspberrypi",
    badgeContent: "Raspberry_Pi",
    color: "A22846",
    logoColor: "white",
  },
  {
    logo: "redis",
    badgeContent: "Redis",
    color: "DC382D",
    logoColor: "white",
  },
  {
    logo: "vim",
    badgeContent: "VIM",
    color: "019733",
    logoColor: "white",
  },
  {
    logo: "visualstudiocode",
    badgeContent: "Visual_Studio_Code",
    color: "0078D4",
    logoColor: "white",
  },
];
